name:                AdventOfCode2020
version:             0.1.0.0
github:              "Periodic/AdventOfCode2020"
license:             BSD3
author:              "Drew Haven"
maintainer:          "drew.haven@gmail.com"
copyright:           "2020 Drew Haven"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/AdventOfCode2020#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec >= 0.13
- text >= 1.0
- containers >= 0.6
- vector >= 0.12
- lens >= 4.0

ghc-options:
- -O
- -rtsopts

default-extensions:
- OverloadedStrings
- GeneralizedNewtypeDeriving
- NamedFieldPuns
- BangPatterns
- GADTs
- LambdaCase
- RankNTypes

library:
  source-dirs: lib
  dependencies:
  - optparse-applicative >= 0.15
  - criterion >= 1.5.7

executables:
  Day01:
    main:                Main.hs
    source-dirs:         Day01
    dependencies:
      - AdventOfCode2020

  Day02:
    main:                Main.hs
    source-dirs:         Day02
    dependencies:
      - AdventOfCode2020

  Day03:
    main:                Main.hs
    source-dirs:         Day03
    dependencies:
      - AdventOfCode2020
      - linear >= 1.21

  Day04:
    main:                Main.hs
    source-dirs:         Day04
    dependencies:
      - AdventOfCode2020

  Day05:
    main:                Main.hs
    source-dirs:         Day05
    dependencies:
      - AdventOfCode2020

  Day06:
    main:                Main.hs
    source-dirs:         Day06
    dependencies:
      - AdventOfCode2020

  Day07:
    main:                Main.hs
    source-dirs:         Day07
    dependencies:
      - AdventOfCode2020

  Day08:
    main:                Main.hs
    source-dirs:         Day08
    dependencies:
      - AdventOfCode2020
      - mtl >= 2.0

  Day09:
    main:                Main.hs
    source-dirs:         Day09
    dependencies:
      - AdventOfCode2020
      
  Day10:
    main:                Main.hs
    source-dirs:         Day10
    dependencies:
      - AdventOfCode2020

  Day11:
    main:                Main.hs
    source-dirs:         Day11
    dependencies:
      - AdventOfCode2020
      - array >= 0.5

  Day12:
    main:                Main.hs
    source-dirs:         Day12
    dependencies:
      - AdventOfCode2020

  Day13:
    main:                Main.hs
    source-dirs:         Day13
    dependencies:
      - AdventOfCode2020

  Day14:
    main:                Main.hs
    source-dirs:         Day14
    dependencies:
      - AdventOfCode2020

  Day15:
    main:                Main.hs
    source-dirs:         Day15
    dependencies:
      - AdventOfCode2020
      - mtl >= 2.0

  Day16:
    main:                Main.hs
    source-dirs:         Day16
    dependencies:
      - AdventOfCode2020

  Day17:
    main:                Main.hs
    source-dirs:         Day17
    dependencies:
      - AdventOfCode2020

  Day18:
    main:                Main.hs
    source-dirs:         Day18
    dependencies:
      - AdventOfCode2020

  Day19:
    main:                Main.hs
    source-dirs:         Day19
    dependencies:
      - AdventOfCode2020
      - mtl >= 2.0

  Day20:
    main:                Main.hs
    source-dirs:         Day20
    dependencies:
      - AdventOfCode2020
      - linear >= 1.21

  Day21:
    main:                Main.hs
    source-dirs:         Day21
    dependencies:
      - AdventOfCode2020

  Day22:
    main:                Main.hs
    source-dirs:         Day22
    dependencies:
      - AdventOfCode2020
      - mtl >= 2.0

  Day23:
    main:                Main.hs
    source-dirs:         Day23
    dependencies:
      - AdventOfCode2020
      - array >= 0.5

  Day24:
    main:                Main.hs
    source-dirs:         Day24
    dependencies:
      - AdventOfCode2020
      - linear >= 1.21

  Day25:
    main:                Main.hs
    source-dirs:         Day25
    dependencies:
      - AdventOfCode2020