name:                AdventOfCode2020
version:             0.1.0.0
github:              "Periodic/AdventOfCode2020"
license:             BSD3
author:              "Drew Haven"
maintainer:          "drew.haven@gmail.com"
copyright:           "2020 Drew Haven"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/AdventOfCode2020#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: src

executables:
  Day01:
    main:                Day01.hs
    source-dirs:         Day01

  Day02:
    main:                Day02.hs
    source-dirs:         Day02
    dependencies:
      - attoparsec >= 0.13
      - text >= 1.0

  Day03:
    main:                Day03.hs
    source-dirs:         Day03
    dependencies:
      - array >= 0.5
      - ilist >= 0.4

  Day04:
    main:                Day04.hs
    source-dirs:         Day04
    dependencies:
      - attoparsec >= 0.13
      - text >= 1.0
      - lens >= 4.0

  Day05:
    main:                Day05.hs
    source-dirs:         Day05